server:
  port: 8081
spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: bhavyagodhaniya2004@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          # Port 465 uses SSL, so starttls should be false
          starttls:
            enable: false
          # SSL Configuration for Render/Production environments
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  kafka:
    bootstrap-servers: smartseat-bhavyagodhaniya2004-2234.k.aivencloud.com:26025

    properties:
      security.protocol: SSL

      schema.registry.url: ${KAFKA_URL}

      basic.auth.credentials.source: USER_INFO
      basic.auth.user.info: ${KAFKA_PASSWORD}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      properties:
        spring.json.value.default.type: java.util.HashMap
        spring.json.trusted.packages: "*"

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.axxwxwxnqteramwkrwrn
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  threads:
    virtual:
      enabled: true
  application:
    name: SmartSeatEmail
