server:
  port: 8081

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: SmartSeatEmail

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: "java.util.HashMap"
        spring.json.trusted.packages: "*"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: bhavyagodhaniya2004@gmail.com # Replace with your Gmail
    password: pidauehekmvbiasv
    # Replace with your 16-digit App Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
